development:
  adapter: postgresql
  encoding: unicode
  database: riffraffle_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: riffraffle_test
  pool: 5

# replaced on deploy by heroku:
production:
  adapter: dummy
