development:
  adapter: postgresql
  encoding: unicode
  database: snow_mobile_raffle_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: snow_mobile_raffle_test
  pool: 5

# replaced on deploy by heroku:
production:
  adapter: dummy
